# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnVer = QtWidgets.QPushButton(self.centralwidget)
        self.btnVer.setGeometry(QtCore.QRect(30, 220, 75, 23))
        self.btnVer.setObjectName("btnVer")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(30, 190, 75, 23))
        self.btnEliminar.setObjectName("btnEliminar")
        self.tblProductos = QtWidgets.QTableView(self.centralwidget)
        self.tblProductos.setGeometry(QtCore.QRect(180, 80, 391, 221))
        self.tblProductos.setObjectName("tblProductos")
        self.lblCodigo = QtWidgets.QLabel(self.centralwidget)
        self.lblCodigo.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.lblCodigo.setObjectName("lblCodigo")
        self.lblMe = QtWidgets.QLabel(self.centralwidget)
        self.lblMe.setGeometry(QtCore.QRect(10, 30, 47, 13))
        self.lblMe.setObjectName("lblMe")
        self.lblCod_Con = QtWidgets.QLabel(self.centralwidget)
        self.lblCod_Con.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.lblCod_Con.setObjectName("lblCod_Con")
        self.lblPrecio = QtWidgets.QLabel(self.centralwidget)
        self.lblPrecio.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.lblPrecio.setObjectName("lblPrecio")
        self.lblCantidad = QtWidgets.QLabel(self.centralwidget)
        self.lblCantidad.setGeometry(QtCore.QRect(0, 100, 47, 13))
        self.lblCantidad.setObjectName("lblCantidad")
        self.lblTotal = QtWidgets.QLabel(self.centralwidget)
        self.lblTotal.setGeometry(QtCore.QRect(10, 120, 47, 13))
        self.lblTotal.setObjectName("lblTotal")
        self.lblFecha = QtWidgets.QLabel(self.centralwidget)
        self.lblFecha.setGeometry(QtCore.QRect(190, 10, 47, 13))
        self.lblFecha.setObjectName("lblFecha")
        self.lblFecha_J = QtWidgets.QLabel(self.centralwidget)
        self.lblFecha_J.setGeometry(QtCore.QRect(190, 30, 47, 13))
        self.lblFecha_J.setObjectName("lblFecha_J")
        self.lblEmpleado = QtWidgets.QLabel(self.centralwidget)
        self.lblEmpleado.setGeometry(QtCore.QRect(190, 50, 47, 13))
        self.lblEmpleado.setObjectName("lblEmpleado")
        self.txtCodigo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCodigo.setGeometry(QtCore.QRect(60, 10, 113, 20))
        self.txtCodigo.setObjectName("txtCodigo")
        self.txtMe = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMe.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.txtMe.setObjectName("txtMe")
        self.txtCod_Conc = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCod_Conc.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.txtCod_Conc.setObjectName("txtCod_Conc")
        self.txtPrecio = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPrecio.setGeometry(QtCore.QRect(60, 70, 113, 20))
        self.txtPrecio.setObjectName("txtPrecio")
        self.txtCantidad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCantidad.setGeometry(QtCore.QRect(60, 100, 113, 20))
        self.txtCantidad.setObjectName("txtCantidad")
        self.txtTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTotal.setGeometry(QtCore.QRect(60, 120, 113, 20))
        self.txtTotal.setObjectName("txtTotal")
        self.txtFecha = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFecha.setGeometry(QtCore.QRect(250, 10, 113, 20))
        self.txtFecha.setObjectName("txtFecha")
        self.txtCod_Jorne = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCod_Jorne.setGeometry(QtCore.QRect(250, 30, 113, 20))
        self.txtCod_Jorne.setObjectName("txtCod_Jorne")
        self.txtCod_Empleado = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCod_Empleado.setGeometry(QtCore.QRect(250, 50, 113, 20))
        self.txtCod_Empleado.setObjectName("txtCod_Empleado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAgregar.setText(_translate("MainWindow", "Agregar"))
        self.btnVer.setText(_translate("MainWindow", "Ver"))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.lblCodigo.setText(_translate("MainWindow", "Codigo"))
        self.lblMe.setText(_translate("MainWindow", "Me"))
        self.lblCod_Con.setText(_translate("MainWindow", "Cod Concepto"))
        self.lblPrecio.setText(_translate("MainWindow", "Precio"))
        self.lblCantidad.setText(_translate("MainWindow", "Cantidad"))
        self.lblTotal.setText(_translate("MainWindow", "total"))
        self.lblFecha.setText(_translate("MainWindow", "Fecha Cobro"))
        self.lblFecha_J.setText(_translate("MainWindow", "Cod Jornada"))
        self.lblEmpleado.setText(_translate("MainWindow", "Cod Empleado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
